services:
  exam-countdown:
    image: ghcr.io/ycy-0510/exam-countdown:latest
    container_name: exam-countdown
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./src/assets:/app/src/assets:ro
