services:
  exam-countdown:
    image: ghcr.io/ycy-0510/exam-countdown:latest
    container_name: exam-countdown
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Asia/Taipei
    env_file:
      - .env
    volumes:
      - ./src/assets:/app/src/assets:ro
      - ./data:/app/data
